repositories:
- name: paulczar
  url: https://tech.paulcz.net/charts

releases:
- name: test-raw
  chart: paulczar/raw
  namespace: default
  wait: true
  atomic: true
  version: "1.0.1"
  values:
    - {{ env "HELMFILE_ENV_DIR" }}/test-raw.yaml.gotmpl

environments:
  default:
  dev:
